### ISSUE TITLE
Delay only working if before spinning

### ISSUE THREAD

**Issue by void-robotics** [ros/rosconsole#11]
Hello,

This works (waits 10 seconds):
```
ROS_WARN_STREAM_DELAYED_THROTTLE(10, "waiting for image data from " << topic);
ros::spinOnce();
```
but this prints out immediately:
```
ros::spinOnce();
ROS_WARN_STREAM_DELAYED_THROTTLE(10, "waiting for image data from " << topic);
```

My assumption is that DELAYED_THROTTLE isn't supposed to work this way.

Although, I'm also finding this isn't working. Note that I have the DELAYED_THROTTLE within a class, but works in "main".

Thanks,
Nathan

**Comment by dirk-thomas** [comment]
The provided snippets don't contain enough context to reproduce the problem. Please provide a [sscce](http://sscce.org/).

**Comment by void-robotics** [comment]
Hi @dirk-thomas ,

I can't seem to reproduce this; but if it comes up again, I'll provide an sscce.
