### ISSUE TITLE
Wrong timestamps in logging output

### ISSUE THREAD

**Issue by hdino** [ros/rosconsole#19]
Hi,

I observed strange timestamps in my logging output and thus created a simple example program:
```
#include <ros/ros.h>

int main(int argc, char **argv)
{
    ros::init(argc, argv, "test_node");
    ros::NodeHandle ros_node_handle;
    ROS_INFO("Hello World");
    return 0;
}
```

Its output looks like this:
`[ INFO] [969709763.000032551]: Hello World`
or
`[ INFO] [1.000000000]: Hello World`

Running the program in `valgrind` showed some problems, but I am not sure whether they are caused by rosconsole, rostime or log4cxx. Here is the [output of valgrind](https://github.com/ros/rosconsole/files/2389781/valgrind.log). Do you have any idea?

**Comment by tfoote** [comment]
What timestamp do you consider strange?

What else is running on your system? Are you running with a source of simulation time? Have you set the `/use_sim_time` parameter? http://wiki.ros.org/Clock

**Comment by hdino** [comment]
The timestamps are just random numbers. Every time I run the program, it will print a completely different timestamp.

Apart from the node only roscore is running. I didn't set any additional parameters, so it should use the computer's wall clock (which is set correctly).

**Comment by tfoote** [comment]
I cannot reproduce this. I reliably see current epoch time when executing your program.

```
tfoote@snowman:/tmp/rosconsole_19 Last: [0] (0s Seconds)
$ rosrun rosconsole_19 rosconsole_19_node 
[ERROR] [1537405215.563962003]: [registerPublisher] Failed to contact master at [localhost:11311].  Retrying...
[ INFO] [1537405223.655759778]: Connected to master at [localhost:11311]
[ INFO] [1537405223.657987566]: Hello World
tfoote@snowman:/tmp/rosconsole_19 Last: [0] (8s Seconds)
$ rosrun rosconsole_19 rosconsole_19_node 
[ INFO] [1537405226.549062635]: Hello World
tfoote@snowman:/tmp/rosconsole_19 Last: [0] (0s Seconds)
$ rosrun rosconsole_19 rosconsole_19_node 
[ INFO] [1537405227.947215768]: Hello World
tfoote@snowman:/tmp/rosconsole_19 Last: [0] (1s Seconds)
$ rosrun rosconsole_19 rosconsole_19_node 
[ INFO] [1537405228.916416115]: Hello World
tfoote@snowman:/tmp/rosconsole_19 Last: [0] (1s Seconds)
$ rosrun rosconsole_19 rosconsole_19_node 
[ INFO] [1537405229.860882226]: Hello World
tfoote@snowman:/tmp/rosconsole_19 Last: [0] (1s Seconds)
$ rosrun rosconsole_19 rosconsole_19_node 
[ INFO] [1537405230.934301298]: Hello World
tfoote@snowman:/tmp/rosconsole_19 Last: [0] (1s Seconds)
$ rosrun rosconsole_19 rosconsole_19_node 
[ INFO] [1537405231.991994000]: Hello World
tfoote@snowman:/tmp/rosconsole_19 Last: [0] (1s Seconds)
$ rosrun rosconsole_19 rosconsole_19_node 
[ INFO] [1537405233.714789541]: Hello World
tfoote@snowman:/tmp/rosconsole_19 Last: [0] (0s Seconds)
```

I'll note that `1.000000000` does not appear to be a random time which is why my question about simulated time.

**Comment by hdino** [comment]
I compiled rosconsole from source and then the problem was gone. Hence, this issue seems to be a problem of the corresponding Debian package. I put it on the [mailing list](https://lists.debian.org/debian-science/2018/09/msg00045.html).

@tfoote Thanks for also looking into this!

**Comment by dirk-thomas** [comment]
@hdino Just to clarify: which exact Debian package are you using? Can you post the full name and version number as well as the apt repo you get it from. There are Debian packages provided by packages.ros.org and some are also upstream in the Debian / Ubuntu repositories (usually older versions).

**Comment by hdino** [comment]
I use the packages from the official Debian testing repositories. Versions are:
librosconsole2d/testing,now 1.13.7-1 amd64
libroscpp2d/testing,now 1.14.2+ds1-7 amd64
librostime0d/testing,now 0.6.11-2 amd64
liblog4cxx10v5/testing,now 0.10.0-15 amd64

I don't know how these version numbers relate to the ROS releases, but I thought they are somewaht up-to-date.

**Comment by dirk-thomas** [comment]
Thanks for clarifying. Than the upstream issue you filled makes the most sense. :+1:
