### ISSUE TITLE
Backport "Force a write of all user-space buffered data for stdout" to kinetic?

### ISSUE THREAD

**Issue by howardcochran** [ros/rosconsole#24]
The commit 71905d78d54c0d58a119bda2bd2ce739b7d3197b, "Force a write of all user-space buffered data for stdout in Formatter::print" added the behavior of flushing stdout for each ROS_LOG when logging to stdout and when the environment variable ROSCONSOLE_STDOUT_LINE_BUFFERED is set to "1".  This behavior is critical for getting timely ROS messages whenever stdout is a pipe (e.g. when it is connected to the systemd journal, or as the author of the commit mentioned, when running in Android).

I would like access to this feature in kinetic.  Since it causes no behavior change unless the referenced environment variable is set, it should cause no compatibility issue. The patch applies cleanly (after accounting for the rename associated with moving rosconsole out of ros_comm to its own repo).

What is the procedure for getting this change into kinetic in the official release?

**Comment by dirk-thomas** [comment]
A new features is commonly not backported to already released distributions. The reason is a combination of effort as well as desire for stability / avoid risk of regressions. For that reason the change was not backported as described in ros/ros_comm#1205.
