### ISSUE TITLE
ROS Console logger level issue

### ISSUE THREAD

**Issue by shannonwarren** [ros/rosconsole#31]
Issue: 

If two ROS Nodes registered with the same name are called one after the other both the nodes shutdown in ROS Melodic however in ROS Kinetic calling the second node with the same node name would shutdown the first node and the second node would run smoothly. 

The same code works well in kinetic however not in melodic it gives us a **_new node registered with the same name error_** and shutsdown both the nodes. Our application requires the second node to run by killing the first node. I suspect its a ros console library issue since changing the ros::console logger level from Warn to Info doesn't shutdown both nodes and runs how we expect it to.

Solution: 
If I change the logger level to Info from _ros::console::levels::Warn/Error/Fatal_ it works well. 

In the ros melodic migration page it is mentioned that the ros_console package is slightly different than the previous versions. 

Need help in understanding this issue. We would like to use the Warn/Error logging levels without the issue we currently have.

**Comment by dirk-thomas** [comment]
Please post reproducible steps.

**Comment by dirk-thomas** [comment]
Closing due to no response.
