### ISSUE TITLE
Undefined reference to 3 types on Eoan / Boost 1.67

### ISSUE THREAD

**Issue by thomasnappee** [ros/rosconsole#39]
Hello

I'm experiencing this issue, trying to build rosconsole from sources.
I don't know what to do... I installed all libboost libraries which are present in my repository.
Thanks in advance

**Error :**

``
tn@pop-os:~/ros_catkin_ws$ cd /home/tn/ros_catkin_ws/build_isolated/rosconsole_bridge && /home/tn/ros_catkin_ws/devel_isolated/rosconsole/env.sh make -j4 -l4
[ 50%] Built target rosconsole_bridge
[ 75%] Linking CXX executable /home/tn/ros_catkin_ws/devel_isolated/rosconsole_bridge/lib/rosconsole_bridge/cleanup
/usr/bin/ld : /home/tn/ros_catkin_ws/devel_isolated/rosconsole/lib/librosconsole.so : référence indéfinie vers « boost::re_detail_106700::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags) »
/usr/bin/ld : /home/tn/ros_catkin_ws/devel_isolated/rosconsole/lib/librosconsole.so : référence indéfinie vers « boost::re_detail_106700::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::find() »
/usr/bin/ld : /home/tn/ros_catkin_ws/devel_isolated/rosconsole/lib/librosconsole.so : référence indéfinie vers « boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::do_assign(char const*, char const*, unsigned int) »
collect2: error: ld returned 1 exit status
make[2]: *** [test/CMakeFiles/cleanup.dir/build.make:97: /home/tn/ros_catkin_ws/devel_isolated/rosconsole_bridge/lib/rosconsole_bridge/cleanup] Error 1
make[1]: *** [CMakeFiles/Makefile2:320: test/CMakeFiles/cleanup.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
``

**g++ version :**

``
g++ (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
``

**OS :**

``
Distributor ID:	Ubuntu
Description:	Pop!_OS 19.10
Release:	19.10
Codename:	eoan
``

**Comment by dirk-thomas** [comment]
First, Ubuntu Eoan isn't an officially supported platform. So you might run into more issues which you need to be comfortable to debug. If that is not the case you might want to consider using a supported platform.

Second: you need to provide more information. What branch / hash of this repo are you trying to build? What version of ROS? What are the steps you have done before?

**Comment by thomasnappee** [comment]
So I'm using this branch : (melodic-devel) 3505c212947224e7630f8b6f59707880d9e59fcf

I'm working with ROS Melodic. Here is the failing command :
``cd /home/tn/ros_catkin_ws/build_isolated/rosconsole_bridge
/home/tn/ros_catkin_ws/devel_isolated/rosconsole/env.sh make -j4 -l4
``

I'm trying to build my catkin workspace. I know that it's not currently supported, but it works on latest raspbian on RPi4 which is not supported too...

Here is the libboost package used, with its version :
``
Package: libboost1.67-all-dev
Version: 1.67.0-13ubuntu1
Priority: optional
Section: universe/libdevel
Source: boost1.67
Origin: Ubuntu
``

**Comment by dirk-thomas** [comment]
The same branch / commit builds fine on Ubuntu Bionic with Boost 1.65 as well as Ubuntu Focal 1.71. I am sorry but I don't have a suggestion for you.

**Comment by thomasnappee** [comment]
Ok I'll look further, thanks

**Comment by dirk-thomas** [comment]
I will go ahead and close the issue for now. Please feel free to follow up with a pull request if you find out how to resolve your problem.
